services:
  github-actions-workflow-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.services.github-actions-workflow-api.loadbalancer.server.port: "8000"
      traefik.http.routers.github-actions-workflow-api.rule: "Host(`sd-api.yhkze.net`)"
      traefik.http.routers.github-actions-workflow-api.service: "github-actions-workflow-api"
      traefik.http.routers.github-actions-workflow-api.entrypoints: "websecure"
      traefik.http.routers.github-actions-workflow-api.tls: "true"

networks:
  traefik:
    external: true
